export const authSchemas = {
  AuthUser: {
    type: "object",
    required: ["id", "email", "role"],
    properties: {
      id: { type: "string", format: "uuid" },
      email: { type: "string", format: "email" },
      role: { type: "string", example: "user" },
    },
  },
  HttpSuccessEnvelope: {
    type: "object",
    required: ["success", "data"],
    description:
      "Canonical success envelope for new JSON endpoints. Auth login/refresh/logout keep the legacy flat `AuthTokens` shape documented below.",
    properties: {
      success: { type: "boolean", enum: [true], example: true },
      data: { description: "Endpoint-specific payload." },
      meta: {
        type: "object",
        additionalProperties: true,
        description: "Optional pagination or diagnostic metadata.",
      },
      requestId: { type: "string", example: "0d2a9475-ccf8-4f03-a64c-ef75f9b2f5c6" },
    },
  },
  RefreshTokenTransport: {
    type: "object",
    description:
      "Refresh token transport for `/auth/refresh`, `/auth/logout`, `/client-auth/refresh`, and `/client-auth/logout`. Accepts `refreshToken` in the JSON body and/or an HttpOnly cookie (`refresh_token` for user auth, `client_refresh_token` for client auth). **Precedence when both are present: body > cookie** — a non-empty body value wins even if the cookie differs.",
    properties: {
      refreshToken: {
        type: "string",
        description:
          "Optional in JSON body. When present and non-empty, takes precedence over the HttpOnly cookie.",
      },
    },
  },
  AuthTokens: {
    type: "object",
    required: ["accessToken", "refreshToken", "success", "token"],
    description:
      "Legacy flat success shape for auth token endpoints (not wrapped in `{ success, data }`). Includes `token` as an alias for `accessToken` for plug_agente compatibility.",
    properties: {
      accessToken: { type: "string" },
      refreshToken: { type: "string" },
      success: { type: "boolean", example: true },
      token: { type: "string", description: "Alias for accessToken" },
    },
  },
  AuthResponse: {
    allOf: [
      { $ref: "#/components/schemas/AuthTokens" },
      {
        type: "object",
        required: ["user"],
        properties: {
          user: { $ref: "#/components/schemas/AuthUser" },
        },
      },
    ],
  },
  AuthChangePasswordRequest: {
    type: "object",
    required: ["currentPassword", "newPassword"],
    properties: {
      currentPassword: { type: "string" },
      newPassword: { type: "string", minLength: 8, maxLength: 128 },
    },
  },
  AgentAuthUser: {
    type: "object",
    required: ["id", "email", "role", "agentId"],
    properties: {
      id: { type: "string", format: "uuid" },
      email: { type: "string", format: "email" },
      role: { type: "string", enum: ["agent"] },
      agentId: { type: "string", format: "uuid" },
    },
  },
  AgentAuthResponse: {
    allOf: [
      { $ref: "#/components/schemas/AuthTokens" },
      {
        type: "object",
        required: ["user"],
        properties: {
          user: { $ref: "#/components/schemas/AgentAuthUser" },
        },
      },
    ],
  },
  ClientAuthUser: {
    type: "object",
    required: ["id", "userId", "email", "name", "lastName", "status", "role"],
    properties: {
      id: { type: "string", format: "uuid" },
      userId: { type: "string", format: "uuid" },
      email: { type: "string", format: "email" },
      name: { type: "string", maxLength: 120 },
      lastName: { type: "string", maxLength: 120 },
      mobile: { type: "string", nullable: true, example: "+5511912345678" },
      thumbnailUrl: {
        type: "string",
        format: "uri",
        nullable: true,
        description: "Normalized thumbnail URL generated by the server.",
      },
      status: { type: "string", enum: ["pending", "active", "rejected", "blocked"] },
      role: { type: "string", enum: ["client"] },
    },
  },
  ClientAuthResponse: {
    allOf: [
      { $ref: "#/components/schemas/AuthTokens" },
      {
        type: "object",
        required: ["client"],
        properties: {
          client: { $ref: "#/components/schemas/ClientAuthUser" },
        },
      },
    ],
  },
  ClientMeResponse: {
    type: "object",
    required: ["client"],
    properties: {
      client: { $ref: "#/components/schemas/ClientAuthUser" },
    },
  },
  ClientPatchMeRequest: {
    type: "object",
    description:
      "Partial profile update. `thumbnailUrl: null` removes the current thumbnail; new thumbnails must be uploaded via `/client-auth/thumbnail`.",
    properties: {
      name: { type: "string", minLength: 1, maxLength: 120 },
      lastName: { type: "string", minLength: 1, maxLength: 120 },
      mobile: {
        oneOf: [
          { type: "string", description: "Brazilian mobile number; normalized to E.164." },
          { type: "null", description: "Remove stored mobile number." },
        ],
      },
      thumbnailUrl: {
        type: "null",
        description:
          "Remove current thumbnail. Use `/client-auth/thumbnail` to upload a new one.",
      },
    },
    additionalProperties: false,
  },
  ClientChangePasswordRequest: {
    type: "object",
    required: ["currentPassword", "newPassword"],
    properties: {
      currentPassword: { type: "string" },
      newPassword: { type: "string", minLength: 8, maxLength: 128 },
    },
  },
  ClientPasswordRecoveryRequest: {
    type: "object",
    required: ["email"],
    properties: {
      email: { type: "string", format: "email" },
    },
  },
  ClientPasswordRecoveryRequestAccepted: {
    type: "object",
    required: ["message"],
    properties: {
      message: {
        type: "string",
        example: "If the account exists, a password recovery email will be sent shortly.",
      },
    },
  },
  ClientPasswordRecoveryStatusResponse: {
    type: "object",
    required: ["status"],
    properties: {
      status: { type: "string", enum: ["pending", "expired"] },
    },
  },
  ClientPasswordRecoveryResetRequest: {
    type: "object",
    required: ["token", "newPassword"],
    properties: {
      token: {
        type: "string",
        minLength: 32,
        maxLength: 128,
        pattern: "^[A-Za-z0-9_-]+$",
      },
      newPassword: { type: "string", minLength: 8, maxLength: 128 },
    },
  },
} as const;
