export const socketEvents = {
  connectionReady: "connection:ready",
  appError: "app:error",
  agentRegister: "agent:register",
  agentCapabilities: "agent:capabilities",
  agentHeartbeat: "agent:heartbeat",
  hubHeartbeatAck: "hub:heartbeat_ack",
  rpcRequest: "rpc:request",
  rpcResponse: "rpc:response",
  rpcRequestAck: "rpc:request_ack",
  rpcBatchAck: "rpc:batch_ack",
  rpcChunk: "rpc:chunk",
  rpcComplete: "rpc:complete",
  rpcStreamPull: "rpc:stream.pull",
  agentsCommand: "agents:command",
  agentsCommandResponse: "agents:command_response",
  agentsCommandStreamChunk: "agents:command_stream_chunk",
  agentsCommandStreamComplete: "agents:command_stream_complete",
  agentsStreamPull: "agents:stream_pull",
  agentsStreamPullResponse: "agents:stream_pull_response",
  relayConversationStart: "relay:conversation.start",
  relayConversationStarted: "relay:conversation.started",
  relayConversationEnd: "relay:conversation.end",
  relayConversationEnded: "relay:conversation.ended",
  relayRpcRequest: "relay:rpc.request",
  relayRpcAccepted: "relay:rpc.accepted",
  relayRpcResponse: "relay:rpc.response",
  relayRpcChunk: "relay:rpc.chunk",
  relayRpcComplete: "relay:rpc.complete",
  relayRpcRequestAck: "relay:rpc.request_ack",
  relayRpcBatchAck: "relay:rpc.batch_ack",
  relayRpcStreamPull: "relay:rpc.stream.pull",
  relayRpcStreamPullResponse: "relay:rpc.stream.pull_response",
} as const;

export const SOCKET_NAMESPACES = {
  agents: "/agents",
  consumers: "/consumers",
} as const;
